# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Starter-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Starter-iOS


  pod 'MBProgressHUD'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'Reqres'
  pod 'AutoCoding'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RealmSwift'
  pod 'REFrostedViewController', '~> 2.4'
#  pod 'AlamofireImage'
  pod 'Kingfisher'
  pod 'AJIBDesignables', :git => 'https://github.com/arunlj561/AJIBDesignables'
end
